title: beginner-python-test
hero_image: images/banner.png
description: beginner-python-test description
theme: cd-green # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "animals, jokes/pranks, space, photography, music/sound, physical computing, games, robots, geography"
technologies: "python"
site_areas:
steps:
  - title: Introduction
  - title: Getting setup
